#!/usr/bin/env bash
commit_regex='(test|TEST)+(-)(\d)+\s+(#)(InProgress|Resolved|Done|Blocked|UAT)+\s+(Add|Cut|Fix|Bump|Make|Start|Stop|Refactor|Reformat|Optimize|Document|Merge)\s+(([a-zA-Z0-9]+)(\s|_)*)+'
error_msg="Commit message format is incorrect. Example: 'dmax-123 #InProgress Add Some changes'"
if ! grep -qE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi

