#!/bin/sh
COMMIT_MESSAGE=$(HEAD -n1 "$1")

CONVENTIONAL_COMMIT_PATTERN="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .+"

if ! [[ "$COMMIT_MESSAGE" =~ $CONVENTIONAL_COMMIT_PATTERN ]]; then
  echo "Error: Your commit message does not comply with this pattern: $CONVENTIONAL_COMMIT_PATTERN"
  echo 'Here are some examples:'
  echo '- "feat: Add user onboarding tutorial"'
  echo '- "fix: Fix chat message overflow"'
  echo '- "chore: Upgrade dependencies"'
  echo '- "refactor: Refactor chat message component"'
  echo '- "docs: Update README"'
  echo '- "test: Add unit tests for chat message component"'
  echo '- "ci: Add CI/CD pipeline"'
  echo '- "build: Add build script"'
  echo '- "style: Enforce code style with custom_lint"'
  echo '- "perf: Improve performance of chat message component"'
  echo '- "revert: Revert "feat: Add user onboarding tutorial""'
  echo "===================================="
  echo "❌ Commit message is invalid..."
  echo "===================================="
  exit 1
else
  echo "===================================="
  echo "✅ Commit message is valid!"
  echo "===================================="
fi