name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# env:
#     SERVICE_NAME: weatherforecasttest

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./src
    steps:
    - uses: actions/checkout@v4

    - name: get repository name in lowercase
      run: |
        echo "REPO_LC=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#davidwallis/}" >> "${GITHUB_ENV}"
        echo "REPOSITORY_NAME1=${REPOSITORY_NAME,,}" >> "${GITHUB_ENV}"
        echo "REPOSITORY_NAME2=${GITHUB_REPOSITORY#davidwallis/}" >> "${GITHUB_ENV}"
        echo "REPOSITORY_NAME3=${REPO_LC#davidwallis/}" >> "${GITHUB_ENV}"

    - name: debug step
      run: echo "$GITHUB_CONTEXT"

    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: 8.0.x

    # - name: Restore dependencies
    #   run: dotnet restore

    # - name: Build
    #   run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

    # - name: Build the Docker image
    #   run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:latest --file WeatherForecastTest/Dockerfile

    # - name: Generate App Version
    #   run: |
    #     # echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
    #     echo APP_VERSION=1.1.1

    # - name: Log into Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Push the image to Docker Hub
    #   if: github.ref == 'refs/heads/main'
    #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}

    # - name: helm package chart
    #   run: |
    #     helm package ../charts/${{ env.REPOSITORY_NAME }} --app-version=${{ env.APP_VERSION }} --version=${{ env.APP_VERSION }} -d ../artifacts

    # - name: helm push chart
    #   if: github.ref == 'refs/heads/main'
    #   # OCI artifacts on Docker Hub
    #   # see: https://docs.docker.com/docker-hub/oci-artifacts/
    #   run: |
    #       helm push ../artifacts/${{ env.REPOSITORY_NAME }}-${{ env.APP_VERSION }}.tgz oci://${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}